apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: compute
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: compute
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 80