{
 "title": "mydash",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Pod Replicas",
   "type": "graph",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas ",
     "legendFormat": "Current Replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_status_desired_replicas ",
     "legendFormat": "Desired Replicas"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 21, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{image!=\"\", namespace=\"default\"}[1m])) by (pod) ",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes", "label": "Usage " }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",namespace=\"default\"}) by (pod)  ",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}